using Domain.Entities;
using Domain.Enum;
using System.Drawing;
using System.Text;

namespace WebApi.Services.ContractToPdf
{
	public class ContractToPdf
	{

		public static string ConverterToHtml(Contract contract)
		{
			StringBuilder Html = new StringBuilder();


			Html.Append(@$" <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:center;line-height:18.75pt;background:white;vertical-align:baseline;'><strong><span style='font-size:26px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>CỘNG XÃ HỘI CHỦ NGHĨA VIỆT NAM</span></strong><span style='font-size:19px;font-family:""Times New Roman"",serif;color:black;'><br>&nbsp;</span><strong><u><span style='font-size:22px;font-family:""Times New Roman"",serif;color:black;'>Độc lập - Tự do - Hạnh phúc</span></u></strong></p>
                            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:center;line-height:18.75pt;background:white;vertical-align:baseline;'><strong><span style='font-size:29px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>&nbsp;</span></strong></p>");

			Html.Append(@$" <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:center;line-height:18.75pt;background:white;vertical-align:baseline;'><strong>
							<span style='font-size:29px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>HỢP ĐỒNG THUÊ PHÒNG - NHÀ TRỌ</span></strong>
							<span style='font-size:19px;font-family:""Times New Roman"",serif;color:black;'><br>&nbsp;</span><em>
							<span style='font-size:22px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>(Số: {contract.Id}/HĐTNT)</span></em></p> 
							<span style='font-size:19px;font-family:""Times New Roman"",serif;color:black;'><br>&nbsp;</span>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Hôm nay, ngày …. tháng …. năm ….., Tại ………………………..Chúng tôi gồm có:</span></p>
							<span style='font-size:10px;font-family:""Times New Roman"",serif;color:black;'><br>&nbsp;</span>");

			Html.Append($@" <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><strong><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>BÊN CHO THUÊ (BÊN A):</span></strong></p>
                            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Ông/bà: {contract.A_Lessor??""}. Ngày sinh: {contract.A_DateOfBirth.ToShortDateString()}.</span></p>
                            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>CMND/CCCD số: {contract.A_Cccd}. Ngày cấp: {contract.A_DateOfIssuance.ToShortDateString()}. Nơi cấp: {contract.A_PlaceOfIssuance}.</span></p>
                            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Địa chỉ thường trú: {contract.A_PermanentAddress}</span></p>
                            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Điện thoại: {contract.A_Phone}</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>&nbsp;</span></p>");

			Html.Append($@" <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><strong><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>BÊN THUÊ (BÊN B):</span></strong></p>
                            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Ông/bà: {contract.B_Lessee??""}. Ngày sinh: {contract.B_DateOfBirth.ToShortDateString()}.</span></p>
                            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>CMND/CCCD số: {contract.B_Cccd}. Ngày cấp: {contract.B_DateOfIssuance.ToShortDateString()}. Nơi cấp: {contract.B_PlaceOfIssuance}.</span></p>
                            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Địa chỉ thường trú: {contract.B_PermanentAddress}</span></p>
                            <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Điện thoại: {contract.B_Phone}</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>&nbsp;</span></p>");

			Html.Append($@" <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><strong><em><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Hai bên cùng thỏa thuận ký hợp đồng với những nội dung sau:</span></em></strong></p> ");

			string houseType =(contract.HouseType==HouseType.Row)? "dãy" : "tầng";

			Html.Append($@" <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Bên A đồng ý cho bên B thuê phòng số {contract.RoomNumber}, {houseType} {contract.AreaName}, nhà trọ {contract.BranchName}, tại địa chỉ: {contract.BranchAddress}. </span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Giá thuê: {contract.RentalPrice}. đ/tháng</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Hình thức thanh toán: ………………………………………………………….</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Tiền điện: ………….đ/kwh tính theo chỉ số công tơ, thanh toán vào cuối các tháng.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Tiền nước: ………….đ/m<sup>2</sup> tính theo chỉ số công tơ, thanh toán vào cuối các tháng.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Tiền đặt cọc: {contract.Deposit}đ.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Hợp đồng có giá trị kể từ ngày {contract.CommencingOn.Day.ToString()} tháng {contract.CommencingOn.Month.ToString()} năm {contract.CommencingOn.Year.ToString()}. 
																																																																																																đến ngày {contract.EndingOn.Day.ToString()} tháng {contract.EndingOn.Month.ToString()} năm {contract.EndingOn.Year.ToString()}</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>&nbsp;</span></p>");

			Html.Append($@" <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><strong><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>TRÁCH NHIỆM CỦA CÁC BÊN</span></strong></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><strong><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>* Trách nhiệm của bên A:</span></strong></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Tạo mọi điều kiện thuận lợi để bên B thực hiện theo hợp đồng.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Cung cấp nguồn điện, nước, wifi cho bên B sử dụng.</span></p>");

			Html.Append($@" <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><strong><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>* Trách nhiệm của bên B:</span></strong></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Thanh toán đầy đủ các khoản tiền theo đúng thỏa thuận.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Bảo quản các trang thiết bị và cơ sở vật chất của bên A trang bị cho ban đầu (làm hỏng phải sửa, mất phải đền).</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Không được tự ý sửa chữa, cải tạo cơ sở vật chất khi chưa được sự đồng ý của bên A.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Giữ gìn vệ sinh trong và ngoài khuôn viên của phòng trọ.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Bên B phải chấp hành mọi quy định của pháp luật Nhà nước và quy định của địa phương.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Nếu bên B cho khách ở qua đêm thì phải báo và được sự đồng ý của chủ nhà đồng thời phải chịu trách nhiệm về các hành vi vi phạm pháp luật của khách trong thời gian ở lại.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>&nbsp;</span></p>
							");

			Html.Append($@" <p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><strong><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>TRÁCH NHIỆM CHUNG</span></strong></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Hai bên phải tạo điều kiện cho nhau thực hiện hợp đồng.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Trong thời gian hợp đồng còn hiệu lực nếu bên nào vi phạm các điều khoản đã thỏa thuận thì bên còn lại có quyền đơn phương chấm dứt hợp đồng; nếu sự vi phạm hợp đồng đó gây tổn thất cho bên bị vi phạm hợp đồng thì bên vi phạm hợp đồng phải bồi thường thiệt hại.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Một trong hai bên muốn chấm dứt hợp đồng trước thời hạn thì phải báo trước cho bên kia ít nhất 30 ngày và hai bên phải có sự thống nhất.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Bên A phải trả lại tiền đặt cọc cho bên B.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Bên nào vi phạm điều khoản chung thì phải chịu trách nhiệm trước pháp luật.</span></p>
							<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:justify;line-height:18.75pt;background:white;vertical-align:baseline;'><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>- Hợp đồng được lập thành 02 bản có giá trị pháp lý như nhau, mỗi bên giữ một bản.</span></p>
							<span style='font-size:19px;font-family:""Times New Roman"",serif;color:black;'><br>&nbsp;</span>");
			Html.Append($@"<table style=""border: none;width:100%;background:white;border-collapse:collapse;"">
							<tbody>
								<tr>
									<td style=""border: none;padding: 1.5pt;height: 48.95pt;vertical-align: bottom;"">
										<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:center;line-height:18.75pt;vertical-align:baseline;'><strong><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Bên thuê</span></strong></p>
										<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:center;line-height:18.75pt;vertical-align:baseline;'><em><span style='font-size:19px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>(Ký, ghi rõ họ tên)</span></em></p>
									</td>
									<td style=""border: none;padding: 1.5pt;height: 48.95pt;vertical-align: bottom;"">
										<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:center;line-height:18.75pt;vertical-align:baseline;'><strong><span style='font-size:27px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>Bên cho thuê</span></strong></p>
										<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;font-size:11.0pt;font-family:""Calibri"",sans-serif;text-align:center;line-height:18.75pt;vertical-align:baseline;'><em><span style='font-size:19px;font-family:""Times New Roman"",serif;color:black;border:none windowtext 1.0pt;padding:0cm;'>(Ký, ghi rõ họ tên)</span></em></p>
									</td>
								</tr>
							</tbody>
						</table>");

			return Html.ToString();
		}

	}
}
